"""creado modificado

Revision ID: 14b4a5510ff7
Revises: 28b1e1676a9e
Create Date: 2023-05-25 09:38:25.638166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b4a5510ff7'
down_revision = '28b1e1676a9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('importers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creado', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('modificado', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('importers', schema=None) as batch_op:
        batch_op.drop_column('modificado')
        batch_op.drop_column('creado')

    # ### end Alembic commands ###
