"""fecha partidos

Revision ID: 2011a854cd8e
Revises: fddf4dd9e99d
Create Date: 2023-07-17 10:31:34.306722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2011a854cd8e'
down_revision = 'fddf4dd9e99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiniela_partidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.String(length=100), nullable=True))

    with op.batch_alter_table('quinigol_partidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quinigol_partidos', schema=None) as batch_op:
        batch_op.drop_column('fecha')

    with op.batch_alter_table('quiniela_partidos', schema=None) as batch_op:
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###
