"""tipo sorteo

Revision ID: 28b1e1676a9e
Revises: af950cb36574
Create Date: 2023-05-24 16:31:53.782811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b1e1676a9e'
down_revision = 'af950cb36574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sorteos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_sorteo', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sorteos', schema=None) as batch_op:
        batch_op.drop_column('tipo_sorteo')

    # ### end Alembic commands ###
