"""importers

Revision ID: 50e51dc938b6
Revises: 5b15122e9543
Create Date: 2023-04-18 08:47:34.567929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e51dc938b6'
down_revision = '5b15122e9543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administraciones', schema=None) as batch_op:
        batch_op.alter_column('cp',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administraciones', schema=None) as batch_op:
        batch_op.alter_column('cp',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
