"""administraciones

Revision ID: 5b15122e9543
Revises: 0ce43f0433f5
Create Date: 2023-03-05 09:48:00.615643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b15122e9543'
down_revision = '0ce43f0433f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administraciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=256), nullable=False),
    sa.Column('contacto', sa.String(length=256), nullable=True),
    sa.Column('codigoSelae', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('movil', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('web', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=256), nullable=True),
    sa.Column('municipio', sa.String(length=256), nullable=True),
    sa.Column('cp', sa.Integer(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('provincia_id', sa.SmallInteger(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('administraciones')
    # ### end Alembic commands ###
