"""field marcador

Revision ID: 689415fc7e75
Revises: 34fa443c07ef
Create Date: 2023-06-05 07:45:52.120728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689415fc7e75'
down_revision = '34fa443c07ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiniela_partidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marcador', sa.String(length=8), nullable=True))
        batch_op.alter_column('local',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=60),
               existing_nullable=True)

    with op.batch_alter_table('quinigol_partidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marcador', sa.String(length=8), nullable=True))
        batch_op.alter_column('local',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=60),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quinigol_partidos', schema=None) as batch_op:
        batch_op.alter_column('local',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
        batch_op.drop_column('marcador')

    with op.batch_alter_table('quiniela_partidos', schema=None) as batch_op:
        batch_op.alter_column('local',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
        batch_op.drop_column('marcador')

    # ### end Alembic commands ###
