"""importers 2

Revision ID: af950cb36574
Revises: 50e51dc938b6
Create Date: 2023-04-18 09:25:45.934307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af950cb36574'
down_revision = '50e51dc938b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('importers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('nombre_sistema', sa.String(length=100), nullable=True),
    sa.Column('tipo_sorteo', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('actualizar_existentes', sa.Boolean(), nullable=True),
    sa.Column('parametro_fecha', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('dias', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_sistema')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('importers')
    # ### end Alembic commands ###
