"""creado modificado

Revision ID: e61ed7271af3
Revises: 14b4a5510ff7
Create Date: 2023-05-25 12:40:19.186214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e61ed7271af3'
down_revision = '14b4a5510ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('importers', schema=None) as batch_op:
        batch_op.alter_column('modificado',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('importers', schema=None) as batch_op:
        batch_op.alter_column('modificado',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
